version: '2'

services:

    api:
        restart: always
        environment:
          - APP_SETTINGS=development
          - PORT=5000
        build:
          context: ./api/.

    web:
        restart: always
        build:
          context: ./web/
        ports:
        - "80:80"
