version: '2'

services:

    api:
        restart: always
        build:
          context: ./api/.

    web:
        restart: always
        build:
          context: ./web/
        ports:
        - "80:80"
